resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/18.yaml

packages:
- .

extra-deps:
  - git: https://github.com/agrafix/aeson-typescript.git
    commit: 1ea2172d9c903d616ed53309a38f136f058dce22
